sudo: false

language: node_js
cache: node_modules

node_js:
  - stable

before_install:
  - npm install
install:
  - npm run build

script:
  - npm run coveralls

deploy:
  provider: npm
  email: d.dodzin@gmail.com
  api_key:
    secure: C5me7IvPlBn4EbP9U6heMZxFKC6WCE5X6zB2mOvoWbHUDBggIxLT6E/8rOvEYSlXCBrgMxR8R7kN33QVBVxi6+PtCW+pKGH3OwpaW1kh1+x4sxzdfOAR8ahp9aDqdU8EnzGCDGhK9VZ4yEi5Z6zEt5aDvII3sWWmfjDVxmQOwji8nQxzehCh6zHrOp1h6FUtkGGvmM4hY8uMLXutqsDdid3MgJrloQuNBC4x5migRUgSPYMTcZ8FvrwDhMnLv1yS0aArafaNPZp3fsq/0NGdlxH7h5kZYbcJB2/DfhWj2H4gb8CDcZHcERMVeDHBjV7niLIfpEYeVa1BbhzGSFNFGupPfji6jDVWtYmw0Cx4xhlGw1TlDMEKdDxJN6aJ2cwpKeo9uGxWxZ7DtWbecp39c8yUgmP+Pp57v6cutWxUrSsKAGjRsKdn4voHioaAsRVeE78vEoJDnEi8xNPDXrM7XEc00IOfBRNP6uMEaIqpoqktEG1/Gdhcvzte/j1ZpakEwRWn1myTxjxOwJuTQaEBx0Lds2fSAc/GouaBb3YvXnmgsTvecqJxgTASnXRP41re4R24C8CL8k4sHxYRmfpKTrQdsZCJwcXPLy5U/FHDB/xMWqk3uP0SJWOsRoSGl0ztRxNr0lPpx641ECInWj6rA08mVpzkIZ8mKDifgeWX3Zs=
  on:
    branch: master
