console.log('                                                  ');
console.log('                        lib-monkey                ');
console.log('                                                  ');
console.log('                         `...` `                  ');
console.log('                      -+::/+oo/:/.                ');
console.log('                     /h/..`.///..+                ');
console.log('                  ``ohy+///+/::/:::/-             ');
console.log('                 ::/+o/----:-:---:-::     `       ');
console.log('                 .--:/--:-.......-:/.   :oyso+.   ');
console.log('             ````..::o+//.-.:-:-:-::`  ohy+/ohy-  ');
console.log('         ./+osssyyhhhhhysss/---:o/.   :hh:  +hh:  ');
console.log('     :::/:::+hhhysso+///hhy+---::sy:  ohy   /+-   ');
console.log('     `/://+::+:-.`      hy/------:hh: yho         ');
console.log('      `::-.`           .ho--------yhy/hho`        ');
console.log('                  `-/+:/h/--------:yhhhhys+       ');
console.log('                 .yhhhhyy----------+hhhhhhh.      ');
console.log('                 /hhhhhhy:---------+hhhhhhs       ');
console.log('                 `+yhhhhho:-------/yhhhss+`       ');
console.log('                  ./ooo+ooo+/::::+sosoo////:`     ');
console.log('                 -/:::-.`  `   .::-::://///-`     ');
console.log('                 `...`          `   `-----        ');
console.log('                                                  ');
console.log('                                                  ');